trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  # Adjust your versioning scheme as needed
  buildConfiguration: 'Release'
  apiProject: 'AspirePlayground.ApiService/AspirePlayground.ApiService.csproj'
  version: '1.0.0.$(Build.BuildId)'
  

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: $(apiProject)

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: $(apiProject)
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack API Service'
  inputs:
    command: 'pack'
    packagesToPack: '$(apiProject)'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'cf0c21e4-1848-49ee-b3bc-c7e03c3de26f'
