trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  # Adjust your versioning scheme as needed
  buildConfiguration: 'Release'
  apiProject: 'AspirePlayground.ApiService/AspirePlayground.ApiService.csproj'
  version: '1.0.0.$(Build.BuildId)'
  nugetSource: 'https://api.nuget.org/v3/index.json'
  # Ensure you add NuGetApiKey as a secure variable in your pipeline settings
  nugetApiKey: $(NuGetApiKey)

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack API Service'
  inputs:
    command: 'pack'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(version)'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    externalFeedUrl: '$(nugetSource)'
    externalFeedPublishKey: '$(nugetApiKey)'
